Update `user_project_wrapper` implementation sdc
efabless/caravel_user_project pull request #278
Opened 2023-06-22 15:18 UTC by passant5

~ update base sdc constraints used for implementation
~ update the example implementation configuration to use the updated sdc and the latest OpenLane

2023-06-25 10:02 UTC, marwaneltoukhy requested changes
Openlane tag needs to get updated in the makefile

2023-07-12 15:32 UTC, marwaneltoukhy approved these changes

2023-07-13 14:58 UTC, marwaneltoukhy requested changes
Flow broke after last update to OpenLane and PDK versions. Needs to be fixed

2023-07-23 16:39 UTC, jeffdi approved these changes

2023-07-23 16:50 UTC, marwaneltoukhy approved these changes

2023-07-23 16:52 UTC, merged