Update Makefile to pip caravel-cocotb-1.1.1
efabless/caravel_user_project pull request #307
Opened 2023-09-20 10:36 UTC by M0stafaRady

new version of caravel-cocotb script. It should fix https://github.com/efabless/caravel_user_project/issues/303

2023-09-20 10:42 UTC, marwaneltoukhy requested changes
Can you add the installation and running inside venv?

2023-09-20 12:35 UTC, marwaneltoukhy requested changes
Looks like you updated the target names, can you update it in the documentation as well? (make sure the you're updating the correct documentation). Also the name of the test from `counter_tests/counter_tests.yaml` to `user_proj_tests/user_proj_tests.yaml`, so you need to update the name of the files.

2023-09-21 07:48 UTC, marwaneltoukhy commented
I get this error 
```
caravel_cocotb -tl user_proj_tests/user_proj_tests.yaml
Run tag: run_21_Sep_10_38_56_85 
Start running test:  RTL-counter_la 
     -.--ns INFO     gpi                                ..mbed/gpi_embed.cpp:76   in set_program_name_in_venv        Did not detect Python virtual environment. Using system-wide Python interpreter
     -.--ns INFO     gpi                                ../gpi/GpiCommon.cpp:101  in gpi_print_registered_impl       VPI registered
/home/marwan/user_project/verilog/dv/cocotb/sim/run_21_Sep_10_38_56_85/RTL-compilation/sim.vvp: Unable to open input file.
Error: Fail to compile the verilog code for more info refer to /home/marwan/user_project/verilog/dv/cocotb/sim/run_21_Sep_10_38_56_85/RTL-compilation/compilation.log
Start running test:  RTL-counter_wb 
     -.--ns INFO     gpi                                ..mbed/gpi_embed.cpp:76   in set_program_name_in_venv        Did not detect Python virtual environment. Using system-wide Python interpreter
     -.--ns INFO     gpi                                ../gpi/GpiCommon.cpp:101  in gpi_print_registered_impl       VPI registered
/home/marwan/user_project/verilog/dv/cocotb/sim/run_21_Sep_10_38_56_85/RTL-compilation/sim.vvp: Unable to open input file.
Error: Fail to compile the verilog code for more info refer to /home/marwan/user_project/verilog/dv/cocotb/sim/run_21_Sep_10_38_56_85/RTL-compilation/compilation.log
Start running test:  RTL-counter_la_reset 
     -.--ns INFO     gpi                                ..mbed/gpi_embed.cpp:76   in set_program_name_in_venv        Did not detect Python virtual environment. Using system-wide Python interpreter
     -.--ns INFO     gpi                                ../gpi/GpiCommon.cpp:101  in gpi_print_registered_impl       VPI registered
/home/marwan/user_project/verilog/dv/cocotb/sim/run_21_Sep_10_38_56_85/RTL-compilation/sim.vvp: Unable to open input file.
Error: Fail to compile the verilog code for more info refer to /home/marwan/user_project/verilog/dv/cocotb/sim/run_21_Sep_10_38_56_85/RTL-compilation/compilation.log
Start running test:  RTL-counter_la_clk 
     -.--ns INFO     gpi                                ..mbed/gpi_embed.cpp:76   in set_program_name_in_venv        Did not detect Python virtual environment. Using system-wide Python interpreter
     -.--ns INFO     gpi                                ../gpi/GpiCommon.cpp:101  in gpi_print_registered_impl       VPI registered
/home/marwan/user_project/verilog/dv/cocotb/sim/run_21_Sep_10_38_56_85/RTL-compilation/sim.vvp: Unable to open input file.
Error: Fail to compile the verilog code for more info refer to /home/marwan/user_project/verilog/dv/cocotb/sim/run_21_Sep_10_38_56_85/RTL-compilation/compilation.log
```
I attached the compilation log, it has errors in the include.
[compilation.log](https://github.com/efabless/caravel_user_project/files/12681791/compilation.log)

2023-09-21 07:55 UTC, M0stafaRady commented
I'm aware of this error. 
This pull request should solve it: https://github.com/efabless/caravel/pull/488

2023-09-24 08:29 UTC, marwaneltoukhy requested changes

2023-09-24 08:29 UTC, marwaneltoukhy commented on Makefile
> +$(info VAR1 is $(cocotb-dv_patterns))
```suggestion

```

2023-09-24 08:40 UTC, marwaneltoukhy approved these changes

2023-09-24 15:23 UTC, jeffdi approved these changes

2023-09-24 15:23 UTC, merged